/* 
 * Insurance API
 *
 * Insurance API Curd Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AgentPatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AgentPatchTests
    {
        // TODO uncomment below to declare an instance variable for AgentPatch
        //private AgentPatch instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AgentPatch
            //instance = new AgentPatch();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AgentPatch
        /// </summary>
        [Test]
        public void AgentPatchInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AgentPatch
            //Assert.IsInstanceOfType<AgentPatch> (instance, "variable 'instance' is a AgentPatch");
        }


        /// <summary>
        /// Test the property 'AgentID'
        /// </summary>
        [Test]
        public void AgentIDTest()
        {
            // TODO unit test for the property 'AgentID'
        }
        /// <summary>
        /// Test the property 'Logo'
        /// </summary>
        [Test]
        public void LogoTest()
        {
            // TODO unit test for the property 'Logo'
        }
        /// <summary>
        /// Test the property 'AgentName'
        /// </summary>
        [Test]
        public void AgentNameTest()
        {
            // TODO unit test for the property 'AgentName'
        }

    }

}
