/* 
 * Insurance API
 *
 * Insurance API Curd Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Policy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PolicyTests
    {
        // TODO uncomment below to declare an instance variable for Policy
        //private Policy instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Policy
            //instance = new Policy();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Policy
        /// </summary>
        [Test]
        public void PolicyInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Policy
            //Assert.IsInstanceOfType<Policy> (instance, "variable 'instance' is a Policy");
        }


        /// <summary>
        /// Test the property 'PolicyID'
        /// </summary>
        [Test]
        public void PolicyIDTest()
        {
            // TODO unit test for the property 'PolicyID'
        }
        /// <summary>
        /// Test the property 'Premium'
        /// </summary>
        [Test]
        public void PremiumTest()
        {
            // TODO unit test for the property 'Premium'
        }
        /// <summary>
        /// Test the property 'Terms'
        /// </summary>
        [Test]
        public void TermsTest()
        {
            // TODO unit test for the property 'Terms'
        }
        /// <summary>
        /// Test the property 'Riders'
        /// </summary>
        [Test]
        public void RidersTest()
        {
            // TODO unit test for the property 'Riders'
        }
        /// <summary>
        /// Test the property 'EffectiveFrom'
        /// </summary>
        [Test]
        public void EffectiveFromTest()
        {
            // TODO unit test for the property 'EffectiveFrom'
        }
        /// <summary>
        /// Test the property 'ActiveTill'
        /// </summary>
        [Test]
        public void ActiveTillTest()
        {
            // TODO unit test for the property 'ActiveTill'
        }

    }

}
