/* 
 * Insurance API
 *
 * Insurance API Curd Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Quote
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuoteTests
    {
        // TODO uncomment below to declare an instance variable for Quote
        //private Quote instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Quote
            //instance = new Quote();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Quote
        /// </summary>
        [Test]
        public void QuoteInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Quote
            //Assert.IsInstanceOfType<Quote> (instance, "variable 'instance' is a Quote");
        }


        /// <summary>
        /// Test the property 'SubmissionNo'
        /// </summary>
        [Test]
        public void SubmissionNoTest()
        {
            // TODO unit test for the property 'SubmissionNo'
        }
        /// <summary>
        /// Test the property 'ApplicantName'
        /// </summary>
        [Test]
        public void ApplicantNameTest()
        {
            // TODO unit test for the property 'ApplicantName'
        }
        /// <summary>
        /// Test the property 'InsuranceType'
        /// </summary>
        [Test]
        public void InsuranceTypeTest()
        {
            // TODO unit test for the property 'InsuranceType'
        }

    }

}
