/* 
 * Insurance API
 *
 * Insurance API Curd Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing QuotePost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class QuotePostTests
    {
        // TODO uncomment below to declare an instance variable for QuotePost
        //private QuotePost instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of QuotePost
            //instance = new QuotePost();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of QuotePost
        /// </summary>
        [Test]
        public void QuotePostInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" QuotePost
            //Assert.IsInstanceOfType<QuotePost> (instance, "variable 'instance' is a QuotePost");
        }


        /// <summary>
        /// Test the property 'EffectiveDate'
        /// </summary>
        [Test]
        public void EffectiveDateTest()
        {
            // TODO unit test for the property 'EffectiveDate'
        }
        /// <summary>
        /// Test the property 'RetroDate'
        /// </summary>
        [Test]
        public void RetroDateTest()
        {
            // TODO unit test for the property 'RetroDate'
        }
        /// <summary>
        /// Test the property 'Zipcode'
        /// </summary>
        [Test]
        public void ZipcodeTest()
        {
            // TODO unit test for the property 'Zipcode'
        }
        /// <summary>
        /// Test the property 'GrossRevenues'
        /// </summary>
        [Test]
        public void GrossRevenuesTest()
        {
            // TODO unit test for the property 'GrossRevenues'
        }
        /// <summary>
        /// Test the property 'NoOfPhysicians'
        /// </summary>
        [Test]
        public void NoOfPhysiciansTest()
        {
            // TODO unit test for the property 'NoOfPhysicians'
        }
        /// <summary>
        /// Test the property 'GL'
        /// </summary>
        [Test]
        public void GLTest()
        {
            // TODO unit test for the property 'GL'
        }
        /// <summary>
        /// Test the property 'EBL'
        /// </summary>
        [Test]
        public void EBLTest()
        {
            // TODO unit test for the property 'EBL'
        }
        /// <summary>
        /// Test the property 'HNOA'
        /// </summary>
        [Test]
        public void HNOATest()
        {
            // TODO unit test for the property 'HNOA'
        }
        /// <summary>
        /// Test the property 'Laser'
        /// </summary>
        [Test]
        public void LaserTest()
        {
            // TODO unit test for the property 'Laser'
        }
        /// <summary>
        /// Test the property 'Retention'
        /// </summary>
        [Test]
        public void RetentionTest()
        {
            // TODO unit test for the property 'Retention'
        }
        /// <summary>
        /// Test the property 'Premium'
        /// </summary>
        [Test]
        public void PremiumTest()
        {
            // TODO unit test for the property 'Premium'
        }

    }

}
