/* 
 * Insurance API
 *
 * Insurance API Curd Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Submission
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionTests
    {
        // TODO uncomment below to declare an instance variable for Submission
        //private Submission instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Submission
            //instance = new Submission();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Submission
        /// </summary>
        [Test]
        public void SubmissionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Submission
            //Assert.IsInstanceOfType<Submission> (instance, "variable 'instance' is a Submission");
        }


        /// <summary>
        /// Test the property 'FromDate'
        /// </summary>
        [Test]
        public void FromDateTest()
        {
            // TODO unit test for the property 'FromDate'
        }
        /// <summary>
        /// Test the property 'ToDate'
        /// </summary>
        [Test]
        public void ToDateTest()
        {
            // TODO unit test for the property 'ToDate'
        }
        /// <summary>
        /// Test the property 'RowsPerPage'
        /// </summary>
        [Test]
        public void RowsPerPageTest()
        {
            // TODO unit test for the property 'RowsPerPage'
        }
        /// <summary>
        /// Test the property 'PrefetchPages'
        /// </summary>
        [Test]
        public void PrefetchPagesTest()
        {
            // TODO unit test for the property 'PrefetchPages'
        }

    }

}
