/* 
 * Insurance API
 *
 * Insurance API Curd Operations
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SubmissionPost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SubmissionPostTests
    {
        // TODO uncomment below to declare an instance variable for SubmissionPost
        //private SubmissionPost instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SubmissionPost
            //instance = new SubmissionPost();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SubmissionPost
        /// </summary>
        [Test]
        public void SubmissionPostInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SubmissionPost
            //Assert.IsInstanceOfType<SubmissionPost> (instance, "variable 'instance' is a SubmissionPost");
        }


        /// <summary>
        /// Test the property 'FromDate'
        /// </summary>
        [Test]
        public void FromDateTest()
        {
            // TODO unit test for the property 'FromDate'
        }
        /// <summary>
        /// Test the property 'ToDate'
        /// </summary>
        [Test]
        public void ToDateTest()
        {
            // TODO unit test for the property 'ToDate'
        }

    }

}
